/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author chido
 */
public class Altas extends javax.swing.JFrame {
  private Registros trabajador;
  int l, regemp1, regemp2, ne, caso, registrostotales;
  String nombus;

  String numero, nom, apellidopaterno, apellidomaterno, direccion, curp, sueldo, diaslab, email, antiguedad;

  /**
   * Creates new form Altas
   */
  public Altas() {
    initComponents();
    // Investigador
    jLabelFacultad.setVisible(false);
    jComboBoxFacultad.setVisible(false);
    jLabelInvestigador.setVisible(false);
    jLabelSNI.setVisible(false);
    jComboBoxNivel.setVisible(false);
    jTextFieldSNI.setVisible(false);
    // Profesor
    jLabelFacultadPertenencia.setVisible(false);
    jComboBoxFacultadPertenencia.setVisible(false);
    jLabelClaseImpartida.setVisible(false);
    jTextFieldClaseImpartida.setVisible(false);
    jLabelHorarioClase.setVisible(false);
    jTextFieldHorarioClase.setVisible(false);
    jLabelNivelProfesor.setVisible(false);
    jComboBoxNivelProfesor.setVisible(false);
    jLabelTitulo.setVisible(false);
    jTextFieldTitulo.setVisible(false);
    // Ayudante
    jLabelFacultadPertenenciaAyudante.setVisible(false);
    jComboBoxFacultadPertenenciaAyudante.setVisible(false);
    jLabelPorcentajeCreditos.setVisible(false);
    jTextFieldPorcentajeCreditos.setVisible(false);
    jLabelNivelAyudante.setVisible(false);
    jComboBoxNivelAyudante.setVisible(false);
    jLabelPasanteoTitulado.setVisible(false);
    jComboBoxPasanteoTitulado.setVisible(false);
    jLabelClaseImpartidaAyudante.setVisible(false);
    jTextFieldClaseImpartidaAyudante.setVisible(false);
    jLabelHorarioClaseAyudante.setVisible(false);
    jTextFieldHorarioAyudante.setVisible(false);
    // Administrativo
    jLabelLugarTrabajoAdmi.setVisible(false);
    jTextFieldLugarTrabajoAdmi.setVisible(false);
    jLabelPuestoAdmi.setVisible(false);
    jTextFieldPuestoAdmi.setVisible(false);
    jLabelHorarioAdmi.setVisible(false);
    jTextFieldHorarioAdmi.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jDialog1 = new javax.swing.JDialog();
    jPanel1 = new javax.swing.JPanel();
    jLabelNombre = new javax.swing.JLabel();
    jTextFieldNombre = new javax.swing.JTextField();
    jLabelPuesto = new javax.swing.JLabel();
    jComboBoxPuesto = new javax.swing.JComboBox<>();
    jLabelApellidopaterno = new javax.swing.JLabel();
    jTextFieldApellidopaterno = new javax.swing.JTextField();
    jLabelApellidomaterno = new javax.swing.JLabel();
    jTextFieldApellidomaterno = new javax.swing.JTextField();
    jLabelNumEmp = new javax.swing.JLabel();
    jTextFieldNumEmp = new javax.swing.JTextField();
    jLabelCURP = new javax.swing.JLabel();
    jTextFieldCURP = new javax.swing.JTextField();
    jLabelDireccion = new javax.swing.JLabel();
    jTextFieldDireccion = new javax.swing.JTextField();
    jLabelSueldoDiario = new javax.swing.JLabel();
    jTextFieldSueldoD = new javax.swing.JTextField();
    jLabelDiasLab = new javax.swing.JLabel();
    jTextFieldDiasLab = new javax.swing.JTextField();
    jLabelEmail = new javax.swing.JLabel();
    jTextFieldEmail = new javax.swing.JTextField();
    jLabelAntiguedad = new javax.swing.JLabel();
    jTextFieldAntiguedad = new javax.swing.JTextField();
    jPanelInvestigador = new javax.swing.JPanel();
    jComboBoxNivel = new javax.swing.JComboBox<>();
    jTextFieldSNI = new javax.swing.JTextField();
    jLabelSNI = new javax.swing.JLabel();
    jLabelFacultad = new javax.swing.JLabel();
    jLabelInvestigador = new javax.swing.JLabel();
    jComboBoxFacultad = new javax.swing.JComboBox<>();
    jPanelProfesor = new javax.swing.JPanel();
    jTextFieldHorarioClase = new javax.swing.JTextField();
    jLabelHorarioClase = new javax.swing.JLabel();
    jLabelFacultadPertenencia = new javax.swing.JLabel();
    jLabelClaseImpartida = new javax.swing.JLabel();
    jComboBoxFacultadPertenencia = new javax.swing.JComboBox<>();
    jTextFieldClaseImpartida = new javax.swing.JTextField();
    jLabelNivelProfesor = new javax.swing.JLabel();
    jComboBoxNivelProfesor = new javax.swing.JComboBox<>();
    jLabelTitulo = new javax.swing.JLabel();
    jTextFieldTitulo = new javax.swing.JTextField();
    jPanelAyudante = new javax.swing.JPanel();
    jLabelNivelAyudante = new javax.swing.JLabel();
    jLabelFacultadPertenenciaAyudante = new javax.swing.JLabel();
    jLabelPorcentajeCreditos = new javax.swing.JLabel();
    jComboBoxFacultadPertenenciaAyudante = new javax.swing.JComboBox<>();
    jTextFieldPorcentajeCreditos = new javax.swing.JTextField();
    jLabelPasanteoTitulado = new javax.swing.JLabel();
    jComboBoxPasanteoTitulado = new javax.swing.JComboBox<>();
    jLabelClaseImpartidaAyudante = new javax.swing.JLabel();
    jTextFieldClaseImpartidaAyudante = new javax.swing.JTextField();
    jComboBoxNivelAyudante = new javax.swing.JComboBox<>();
    jLabelHorarioClaseAyudante = new javax.swing.JLabel();
    jTextFieldHorarioAyudante = new javax.swing.JTextField();
    jPanelAdministrativo = new javax.swing.JPanel();
    jLabelLugarTrabajoAdmi = new javax.swing.JLabel();
    jLabelPuestoAdmi = new javax.swing.JLabel();
    jTextFieldPuestoAdmi = new javax.swing.JTextField();
    jLabelHorarioAdmi = new javax.swing.JLabel();
    jTextFieldHorarioAdmi = new javax.swing.JTextField();
    jTextFieldLugarTrabajoAdmi = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButtonCancelar = new javax.swing.JButton();

    javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
    jDialog1.getContentPane().setLayout(jDialog1Layout);
    jDialog1Layout.setHorizontalGroup(
        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
    jDialog1Layout.setVerticalGroup(
        jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMaximumSize(new java.awt.Dimension(10000, 10000));
    setPreferredSize(new java.awt.Dimension(600, 650));

    jPanel1.setName(""); // NOI18N
    jPanel1.setPreferredSize(new java.awt.Dimension(200, 1040));

    jLabelNombre.setText("Nombre(s)");

    jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldNombreActionPerformed(evt);
      }
    });

    jLabelPuesto.setText("Puesto: ");

    jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Investigador", "Profesor", "Ayudante", "Administrativo", "Seleccionar", " " }));
    jComboBoxPuesto.setSelectedIndex(4);
    jComboBoxPuesto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxPuestoActionPerformed(evt);
      }
    });

    jLabelApellidopaterno.setText("Apellido paterno:");

    jTextFieldApellidopaterno.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldApellidopaternoActionPerformed(evt);
      }
    });

    jLabelApellidomaterno.setText("Apellido Materno:");

    jTextFieldApellidomaterno.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldApellidomaternoActionPerformed(evt);
      }
    });

    jLabelNumEmp.setText("Numero de trabajador:");

    jTextFieldNumEmp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldNumEmpActionPerformed(evt);
      }
    });

    jLabelCURP.setText("CURP:");

    jTextFieldCURP.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldCURPActionPerformed(evt);
      }
    });

    jLabelDireccion.setText("Dirección:");

    jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldDireccionActionPerformed(evt);
      }
    });

    jLabelSueldoDiario.setText("Sueldo diario:");

    jTextFieldSueldoD.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldSueldoDActionPerformed(evt);
      }
    });

    jLabelDiasLab.setText("Dias Laboradorados:");

    jTextFieldDiasLab.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldDiasLabActionPerformed(evt);
      }
    });

    jLabelEmail.setText("Correo Electronico:");

    jTextFieldEmail.setMaximumSize(new java.awt.Dimension(10000, 10000));
    jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldEmailActionPerformed(evt);
      }
    });

    jLabelAntiguedad.setText("Años de antiguedad:");

    jTextFieldAntiguedad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldAntiguedadActionPerformed(evt);
      }
    });

    jPanelInvestigador.setMaximumSize(new java.awt.Dimension(500, 500));

    jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "Seleccionar" }));
    jComboBoxNivel.setSelectedIndex(3);
    jComboBoxNivel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxNivelActionPerformed(evt);
      }
    });

    jTextFieldSNI.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldSNIActionPerformed(evt);
      }
    });

    jLabelSNI.setText("Nivel de SNI: ");

    jLabelFacultad.setText("Facultad a la que pertenece: ");

    jLabelInvestigador.setText("Nivel de investigador: ");

    jComboBoxFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultad de Arquitectura",
        "Facultad de Artes y Diseño", "Facultad de Ciencias", "Facultad de Ciencias Políticas y Sociales",
        "Facultad de Contaduría y Administración", "Facultad de Derecho", "Facultad de Economía",
        "Facultad de Estudios Superiores (FES) Acatlán", "Facultad de Estudios Superiores (FES) Aragón",
        "Facultad de Estudios Superiores (FES) Cuautitlán", "Facultad de Estudios Superiores (FES) Iztacala",
        "Facultad de Estudios Superiores (FES) Zaragoza", "Facultad de Filosofía y Letras", "Facultad de Ingeniería",
        "Facultad de Medicina", "Facultad de Medicina Veterinaria y Zootecnia", "Facultad de Música",
        "Facultad de Odontología", "Facultad de Psicología", "Facultad de Química", "Seleccionar" }));
    jComboBoxFacultad.setSelectedIndex(20);
    jComboBoxFacultad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxFacultadActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelInvestigadorLayout = new javax.swing.GroupLayout(jPanelInvestigador);
    jPanelInvestigador.setLayout(jPanelInvestigadorLayout);
    jPanelInvestigadorLayout.setHorizontalGroup(jPanelInvestigadorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelInvestigadorLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInvestigadorLayout.createSequentialGroup().addComponent(jLabelInvestigador)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxNivel,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInvestigadorLayout.createSequentialGroup().addComponent(jLabelSNI)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldSNI,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInvestigadorLayout.createSequentialGroup().addComponent(jLabelFacultad)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxFacultad,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap()));
    jPanelInvestigadorLayout.setVerticalGroup(jPanelInvestigadorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelInvestigadorLayout.createSequentialGroup().addGap(10, 10, 10)
            .addGroup(jPanelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelFacultad).addComponent(jComboBoxFacultad, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelInvestigador).addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelSNI).addComponent(jTextFieldSNI, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap()));

    jTextFieldHorarioClase.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldHorarioClaseActionPerformed(evt);
      }
    });

    jLabelHorarioClase.setText("Horario de la clase:");

    jLabelFacultadPertenencia.setText("Facultad donde imparte clase: ");

    jLabelClaseImpartida.setText("Clase que imparte:");

    jComboBoxFacultadPertenencia.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Facultad de Arquitectura", "Facultad de Artes y Diseño", "Facultad de Ciencias",
            "Facultad de Ciencias Políticas y Sociales", "Facultad de Contaduría y Administración",
            "Facultad de Derecho", "Facultad de Economía", "Facultad de Estudios Superiores (FES) Acatlán",
            "Facultad de Estudios Superiores (FES) Aragón", "Facultad de Estudios Superiores (FES) Cuautitlán",
            "Facultad de Estudios Superiores (FES) Iztacala", "Facultad de Estudios Superiores (FES) Zaragoza",
            "Facultad de Filosofía y Letras", "Facultad de Ingeniería", "Facultad de Medicina",
            "Facultad de Medicina Veterinaria y Zootecnia", "Facultad de Música", "Facultad de Odontología",
            "Facultad de Psicología", "Facultad de Química", "Seleccionar" }));
    jComboBoxFacultadPertenencia.setSelectedIndex(20);
    jComboBoxFacultadPertenencia.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxFacultadPertenenciaActionPerformed(evt);
      }
    });

    jLabelNivelProfesor.setText("Nivel de profesor");

    jComboBoxNivelProfesor
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "Seleccionar" }));
    jComboBoxNivelProfesor.setSelectedIndex(3);

    jLabelTitulo.setText("Titulo");

    javax.swing.GroupLayout jPanelProfesorLayout = new javax.swing.GroupLayout(jPanelProfesor);
    jPanelProfesor.setLayout(jPanelProfesorLayout);
    jPanelProfesorLayout.setHorizontalGroup(jPanelProfesorLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelProfesorLayout.createSequentialGroup().addContainerGap().addGroup(jPanelProfesorLayout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addComponent(jLabelFacultadPertenencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxFacultadPertenencia, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addComponent(jLabelClaseImpartida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClaseImpartida))
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addComponent(jLabelHorarioClase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHorarioClase, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addComponent(jLabelNivelProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxNivelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldTitulo)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    jPanelProfesorLayout
        .setVerticalGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfesorLayout.createSequentialGroup().addContainerGap()
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFacultadPertenencia).addComponent(jComboBoxFacultadPertenencia,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClaseImpartida).addComponent(jTextFieldClaseImpartida,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorarioClase).addComponent(jTextFieldHorarioClase,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNivelProfesor).addComponent(jComboBoxNivelProfesor,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo).addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jLabelNivelAyudante.setText("Nivel de ayudante:");

    jLabelFacultadPertenenciaAyudante.setText("Facultad donde imparte clase: ");

    jLabelPorcentajeCreditos.setText("Porcentaje de creditos:");

    jComboBoxFacultadPertenenciaAyudante.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] { "Facultad de Arquitectura", "Facultad de Artes y Diseño", "Facultad de Ciencias",
            "Facultad de Ciencias Políticas y Sociales", "Facultad de Contaduría y Administración",
            "Facultad de Derecho", "Facultad de Economía", "Facultad de Estudios Superiores (FES) Acatlán",
            "Facultad de Estudios Superiores (FES) Aragón", "Facultad de Estudios Superiores (FES) Cuautitlán",
            "Facultad de Estudios Superiores (FES) Iztacala", "Facultad de Estudios Superiores (FES) Zaragoza",
            "Facultad de Filosofía y Letras", "Facultad de Ingeniería", "Facultad de Medicina",
            "Facultad de Medicina Veterinaria y Zootecnia", "Facultad de Música", "Facultad de Odontología",
            "Facultad de Psicología", "Facultad de Química", "Seleccionar" }));
    jComboBoxFacultadPertenenciaAyudante.setSelectedIndex(20);

    jLabelPasanteoTitulado.setText("Pasante o Titulado:");

    jComboBoxPasanteoTitulado
        .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasante", "Titulado", "Seleccionar", " " }));
    jComboBoxPasanteoTitulado.setSelectedIndex(2);

    jLabelClaseImpartidaAyudante.setText("Clase que imparte");

    jComboBoxNivelAyudante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "Seleccionar" }));
    jComboBoxNivelAyudante.setSelectedIndex(2);

    jLabelHorarioClaseAyudante.setText("Horario de la clase:");

    javax.swing.GroupLayout jPanelAyudanteLayout = new javax.swing.GroupLayout(jPanelAyudante);
    jPanelAyudante.setLayout(jPanelAyudanteLayout);
    jPanelAyudanteLayout.setHorizontalGroup(jPanelAyudanteLayout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelAyudanteLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(
                        jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelFacultadPertenenciaAyudante)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxFacultadPertenenciaAyudante, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelPasanteoTitulado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPasanteoTitulado, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelClaseImpartidaAyudante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldClaseImpartidaAyudante))
                    .addGroup(jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelPorcentajeCreditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPorcentajeCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelNivelAyudante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNivelAyudante, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelAyudanteLayout.createSequentialGroup().addComponent(jLabelHorarioClaseAyudante)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldHorarioAyudante, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
                        javax.swing.GroupLayout.PREFERRED_SIZE)))));
    jPanelAyudanteLayout
        .setVerticalGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAyudanteLayout.createSequentialGroup().addContainerGap()
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFacultadPertenenciaAyudante).addComponent(jComboBoxFacultadPertenenciaAyudante,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorcentajeCreditos).addComponent(jTextFieldPorcentajeCreditos,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNivelAyudante).addComponent(jComboBoxNivelAyudante,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasanteoTitulado).addComponent(jComboBoxPasanteoTitulado,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClaseImpartidaAyudante).addComponent(jTextFieldClaseImpartidaAyudante,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAyudanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorarioClaseAyudante).addComponent(jTextFieldHorarioAyudante,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))));

    jLabelLugarTrabajoAdmi.setText("Lugar de trabajo:");

    jLabelPuestoAdmi.setText("Puesto:");

    jLabelHorarioAdmi.setText("Horario:");

    javax.swing.GroupLayout jPanelAdministrativoLayout = new javax.swing.GroupLayout(jPanelAdministrativo);
    jPanelAdministrativo.setLayout(jPanelAdministrativoLayout);
    jPanelAdministrativoLayout
        .setHorizontalGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministrativoLayout.createSequentialGroup().addContainerGap()
                .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdministrativoLayout.createSequentialGroup().addComponent(jLabelLugarTrabajoAdmi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldLugarTrabajoAdmi))
                    .addGroup(jPanelAdministrativoLayout.createSequentialGroup()
                        .addGroup(jPanelAdministrativoLayout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelAdministrativoLayout.createSequentialGroup().addComponent(jLabelHorarioAdmi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHorarioAdmi))
                            .addGroup(jPanelAdministrativoLayout.createSequentialGroup().addComponent(jLabelPuestoAdmi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPuestoAdmi, javax.swing.GroupLayout.PREFERRED_SIZE, 124,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap()));
    jPanelAdministrativoLayout
        .setVerticalGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdministrativoLayout.createSequentialGroup().addContainerGap()
                .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugarTrabajoAdmi).addComponent(jTextFieldLugarTrabajoAdmi,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPuestoAdmi).addComponent(jTextFieldPuestoAdmi,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdministrativoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorarioAdmi).addComponent(jTextFieldHorarioAdmi,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jButton1.setBackground(new java.awt.Color(153, 204, 255));
    jButton1.setText("Guardar");
    jButton1.setPreferredSize(new java.awt.Dimension(130, 40));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButtonCancelar.setText("Cancelar");
    jButtonCancelar.setPreferredSize(new java.awt.Dimension(130, 40));
    jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonCancelarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAdministrativo, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabelNombre)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldNombre,
                        javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabelAntiguedad)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextFieldAntiguedad, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelDiasLab)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDiasLab))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelSueldoDiario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldSueldoD, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabelPuesto)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jComboBoxPuesto,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelDireccion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDireccion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelCURP)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCURP))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelNumEmp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNumEmp))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelApellidomaterno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldApellidomaterno))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                        jPanel1Layout.createSequentialGroup().addComponent(jLabelApellidopaterno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldApellidopaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 305,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanelInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jPanelAyudante, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
            jPanel1Layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18).addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)));
    jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup().addGap(8, 8, 8)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelNombre).addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelApellidopaterno).addComponent(jTextFieldApellidopaterno,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelApellidomaterno).addComponent(jTextFieldApellidomaterno,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelNumEmp).addComponent(jTextFieldNumEmp, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelCURP).addComponent(jTextFieldCURP, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelDireccion).addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelSueldoDiario).addComponent(jTextFieldSueldoD,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelDiasLab).addComponent(jTextFieldDiasLab, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelEmail).addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelAntiguedad).addComponent(jTextFieldAntiguedad,
                    javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelPuesto).addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanelAyudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12)
            .addComponent(jPanelAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE).addContainerGap()));

    pack();
  }// </editor-fold>

  private void jTextFieldHorarioClaseActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldSNIActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldDiasLabActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldSueldoDActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldCURPActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldNumEmpActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldApellidomaternoActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jTextFieldApellidopaternoActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jComboBoxPuestoActionPerformed(java.awt.event.ActionEvent evt) {

    int opcion = jComboBoxPuesto.getSelectedIndex();

    switch (opcion) {
      case 0:

        jPanelInvestigador.setVisible(true);
        jPanelProfesor.setVisible(false);
        jPanelAyudante.setVisible(false);
        jPanelAdministrativo.setVisible(false);
        jLabelFacultad.setVisible(true);
        jComboBoxFacultad.setVisible(true);
        jLabelInvestigador.setVisible(true);
        jLabelSNI.setVisible(true);
        jComboBoxNivel.setVisible(true);
        jTextFieldSNI.setVisible(true);
        break;
      case 1:

        jPanelProfesor.setVisible(true);
        jPanelAyudante.setVisible(false);
        jPanelAdministrativo.setVisible(false);
        jPanelInvestigador.setVisible(false);
        jLabelFacultadPertenencia.setVisible(true);
        jComboBoxFacultadPertenencia.setVisible(true);
        jLabelClaseImpartida.setVisible(true);
        jTextFieldClaseImpartida.setVisible(true);
        jLabelHorarioClase.setVisible(true);
        jTextFieldHorarioClase.setVisible(true);
        jLabelNivelProfesor.setVisible(true);
        jComboBoxNivelProfesor.setVisible(true);
        jLabelTitulo.setVisible(true);
        jTextFieldTitulo.setVisible(true);
        break;
      case 2:

        jPanelAyudante.setVisible(true);
        jPanelInvestigador.setVisible(false);
        jPanelProfesor.setVisible(false);
        jPanelAdministrativo.setVisible(false);
        jLabelFacultadPertenenciaAyudante.setVisible(true);
        jComboBoxFacultadPertenenciaAyudante.setVisible(true);
        jLabelPorcentajeCreditos.setVisible(true);
        jTextFieldPorcentajeCreditos.setVisible(true);
        jLabelNivelAyudante.setVisible(true);
        jComboBoxNivelAyudante.setVisible(true);
        jLabelPasanteoTitulado.setVisible(true);
        jComboBoxPasanteoTitulado.setVisible(true);
        jLabelClaseImpartidaAyudante.setVisible(true);
        jTextFieldClaseImpartidaAyudante.setVisible(true);
        jLabelHorarioClaseAyudante.setVisible(true);
        jTextFieldHorarioAyudante.setVisible(true);
        break;
      case 3:
        jPanelAdministrativo.setVisible(true);
        jPanelInvestigador.setVisible(false);
        jPanelProfesor.setVisible(false);
        jPanelAyudante.setVisible(false);
        jLabelLugarTrabajoAdmi.setVisible(true);
        jTextFieldLugarTrabajoAdmi.setVisible(true);
        jLabelPuestoAdmi.setVisible(true);
        jTextFieldPuestoAdmi.setVisible(true);
        jLabelHorarioAdmi.setVisible(true);
        jTextFieldHorarioAdmi.setVisible(true);
        break;
      case 4:
        jPanelInvestigador.setVisible(false);
        jPanelProfesor.setVisible(false);
        jPanelAyudante.setVisible(false);
        jPanelAdministrativo.setVisible(false);
        break;
    }
  }

  private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {
    dispose();
  }

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    int opcion = jComboBoxPuesto.getSelectedIndex();
    // registrostotales = trabajador.longitud();
    String numero = jTextFieldNumEmp.getText();
    String nom = jTextFieldNombre.getText();
    // System.out.println("\nRegistros totales: " + registrostotales);
    System.out.println("\n Se agrego a " + nom);
    String apellidopaterno = jTextFieldApellidopaterno.getText();
    String apellidomaterno = jTextFieldApellidomaterno.getText();
    String direccion = jTextFieldDireccion.getText();
    String curp = jTextFieldCURP.getText();
    String sueldo = jTextFieldSueldoD.getText();
    String diaslab = jTextFieldDiasLab.getText();
    String email = jTextFieldEmail.getText();
    String antiguedad = jTextFieldAntiguedad.getText();
    String todos = nom + " " + apellidopaterno + " " + apellidomaterno + " " + direccion + " " + curp + " " + sueldo
        + " " + diaslab + " " + email + " " + antiguedad + " ";
    switch (opcion) {
      case 0:
        todos += jComboBoxFacultad.getItemAt(jComboBoxFacultad.getSelectedIndex()) + " "
            + jComboBoxNivel.getItemAt(jComboBoxNivel.getSelectedIndex()) + " " + jTextFieldSNI.getText();
        break;
      case 1:
        todos += jComboBoxFacultadPertenencia.getItemAt(jComboBoxFacultadPertenencia.getSelectedIndex()) + " "
            + jTextFieldClaseImpartida.getText() + " " + jTextFieldHorarioClase.getText()
            + jComboBoxNivelProfesor.getItemAt(jComboBoxNivelProfesor.getSelectedIndex()) + " "
            + jTextFieldTitulo.getText();
        break;
      case 2:
        todos += jComboBoxFacultadPertenenciaAyudante.getItemAt(jComboBoxFacultadPertenenciaAyudante.getSelectedIndex())
            + " " + jTextFieldPorcentajeCreditos.getText() + " "
            + jComboBoxNivelAyudante.getItemAt(jComboBoxNivelAyudante.getSelectedIndex()) + " "
            + jComboBoxPasanteoTitulado.getItemAt(jComboBoxPasanteoTitulado.getSelectedIndex()) + " "
            + jTextFieldClaseImpartidaAyudante.getText() + " " + jTextFieldHorarioAyudante.getText();
      case 3:
        todos += jTextFieldLugarTrabajoAdmi.getText() + " " + jTextFieldPuestoAdmi.getText() + " "
            + jTextFieldHorarioAdmi.getText();
    }

    /*
     * int numeroe = Integer.parseInt(numero); int dias = Integer.parseInt(diaslab);
     * Float sueldo1 = Float.parseFloat(sueldo); Float sueldototal = sueldo1 * dias;
     */
    try {
      FileWriter file = new FileWriter("Nomina.txt", true);
      BufferedWriter writer = new BufferedWriter(file);
      writer.write(todos + "\n ");
      writer.close();
    } catch (IOException ex) {
    }

    dispose();
    JOptionPane.showMessageDialog(null, "El archivo se ha guardado correctamente");
    /*
     * trabajador.nuevoReg(new Empleado(nom, apellidopaterno, apellidomaterno,
     * numeroe, direccion, curp, sueldo1, dias, sueldototal, email, antiguedad));
     * JOptionPane.showMessageDialog(null,
     * "El archivo se ha guardado correctamente"); jDialog1.setVisible(false); }
     * else if (caso == 2) { regemp2 = trabajador.buscar(nombus, regemp1 + 1); if
     * (regemp2 < 0) { JOptionPane.showMessageDialog(null,
     * "No existen coincidencias"); jButton1.setText("Nueva búsqueda"); caso = 5; }
     * else if (regemp2 >= 0 && regemp2 < l) { jDialog1.setVisible(true); //
     * jLabelSueldoTotal.setVisible(true); //
     * jTextFieldSueldoTotal.setVisible(true);
     * 
     * String numeroemp = String.valueOf(trabajador.registro(regemp2).getNumEmp());
     * 
     * String sueldodia =
     * String.valueOf(trabajador.registro(regemp2).getSueldoDiario()); String
     * diastra = String.valueOf(trabajador.registro(regemp2).getDiasLab()); String
     * sueldotot = String.valueOf(trabajador.registro(regemp2).getSueldoTotal());
     * 
     * jTextFieldNumEmp.setText(numeroemp);
     * 
     * jTextFieldNombre.setText(trabajador.registro(regemp2).getNombre());
     * jTextFieldApellidopaterno.setText(trabajador.registro(regemp2).
     * getApellidopaterno());
     * jTextFieldApellidomaterno.setText(trabajador.registro(regemp2).
     * getApellidomaterno());
     * jTextFieldDireccion.setText(trabajador.registro(regemp2).getDireccion());
     * jTextFieldCURP.setText(trabajador.registro(regemp2).getCurp());
     * jTextFieldSueldoD.setText(sueldodia); jTextFieldDiasLab.setText(diastra); //
     * jTextFieldSueldoTotal.setText(sueldotot);
     * jTextFieldEmail.setText(trabajador.registro(regemp2).getEmail());
     * jTextFieldAntiguedad.setText(trabajador.registro(regemp2).getAntiguedad());
     * regemp1 = regemp2; } } else if (caso == 3) { trabajador.eliminarReg(ne);
     * jDialog1.setVisible(false); JOptionPane.showMessageDialog(null,
     * "Registro eliminado"); } else if (caso == 4) { String numero =
     * jTextFieldNumEmp.getText();
     * 
     * String sueldo = jTextFieldSueldoD.getText(); String diaslab =
     * jTextFieldDiasLab.getText(); int numeroe = Integer.parseInt(numero); Float
     * sueldo1 = Float.parseFloat(sueldo); int diasl = Integer.parseInt(diaslab);
     * Float sueldotot = sueldo1 * diasl;
     * 
     * trabajador.registro(regemp1).setNumemp(numeroe);
     * 
     * trabajador.registro(regemp1).setNombre(jTextFieldNombre.getText());
     * trabajador.registro(regemp1).setApellidopaterno(jTextFieldApellidopaterno.
     * getText());
     * trabajador.registro(regemp1).setApellidomaterno(jTextFieldApellidomaterno.
     * getText());
     * trabajador.registro(regemp1).setDireccion(jTextFieldDireccion.getText());
     * trabajador.registro(regemp1).setCurp(jTextFieldCURP.getText());
     * trabajador.registro(regemp1).setSueldoDiario(sueldo1);
     * trabajador.registro(regemp1).setDiasLab(diasl);
     * trabajador.registro(regemp1).setSueldoTotal(sueldotot);
     * trabajador.registro(regemp1).setEmail(jTextFieldEmail.getText());
     * trabajador.registro(regemp1).setAntiguedad(jTextFieldAntiguedad.getText());
     * 
     * jDialog1.setVisible(false); JOptionPane.showMessageDialog(null,
     * "Registro actualizado"); } else buscar();
     */
  }

  private void jComboBoxFacultadActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jComboBoxNivelActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void jComboBoxFacultadPertenenciaActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  /**
   * El método buscar se utilizará en 3 casos: 1. En la opción "Buscar" del Menú
   * "Registro" 2. En el botón "Buscar siguiente" del cuadro de diálogo "Buscar"
   * 3. En el botón "Nueva búsqueda" del cuadro de diálogo "Buscar", esta opción
   * se activa cuando "Buscar siguiente" devuelve "No existen coincidencias"
   */
  public void buscar() {
    nombus = JOptionPane.showInputDialog("Escriba el nombre a buscar: ");
    regemp1 = trabajador.buscar(nombus, 0);

    l = trabajador.longitud();
    if (l == 0)
      JOptionPane.showMessageDialog(null, "Lista vacía");

    else if (regemp1 == -1)
      JOptionPane.showMessageDialog(null, "No se encontró ningún registro");
    else {
      jDialog1.setTitle("Buscar");
      jButton1.setText("Buscar siguiente");
      // jLabelSueldoTotal.setVisible(true);
      // jTextFieldSueldoTotal.setVisible(true);

      String numeroemp = String.valueOf(trabajador.registro(regemp1).getNumEmp());

      String sueldodia = String.valueOf(trabajador.registro(regemp1).getSueldoDiario());
      String diastra = String.valueOf(trabajador.registro(regemp1).getDiasLab());
      String sueldotot = String.valueOf(trabajador.registro(regemp1).getSueldoTotal());

      jTextFieldNumEmp.setText(numeroemp);

      jTextFieldNombre.setText(trabajador.registro(regemp1).getNombre());
      jTextFieldApellidopaterno.setText(trabajador.registro(regemp1).getApellidopaterno());
      jTextFieldApellidomaterno.setText(trabajador.registro(regemp1).getApellidomaterno());
      jTextFieldDireccion.setText(trabajador.registro(regemp1).getDireccion());
      jTextFieldCURP.setText(trabajador.registro(regemp1).getCurp());
      jTextFieldSueldoD.setText(sueldodia);
      jTextFieldDiasLab.setText(diastra);
      // jTextFieldSueldoTotal.setText(sueldotot);
      jTextFieldEmail.setText(trabajador.registro(regemp1).getEmail());
      jTextFieldAntiguedad.setText(trabajador.registro(regemp1).getAntiguedad());
      caso = 2;
      jDialog1.setVisible(true);
    }
  }

  // Metodo para cambiar datos de un empleado
  public void actualizar() {
    nombus = JOptionPane.showInputDialog("Escriba el numero del Trabajador que desea modificar: ");

    int numeroe = Integer.parseInt(nombus);

    regemp1 = trabajador.buscarParaCam(numeroe);
    if (regemp1 == -1)
      JOptionPane.showMessageDialog(null, "No se encontró ningún registro");
    else {
      jDialog1.setLocation(400, 200);
      jDialog1.setTitle("Actualizar");
      jButton1.setText("Guardar cambios");
      String numeroE = String.valueOf(trabajador.registro(regemp1).getNumEmp());

      String sueldoD = String.valueOf(trabajador.registro(regemp1).getSueldoDiario());
      String diasl = String.valueOf(trabajador.registro(regemp1).getDiasLab());
      jTextFieldNumEmp.setText(numeroE);

      jTextFieldNombre.setText(trabajador.registro(regemp1).getNombre());
      jTextFieldApellidopaterno.setText(trabajador.registro(regemp1).getApellidopaterno());
      jTextFieldApellidomaterno.setText(trabajador.registro(regemp1).getApellidomaterno());
      jTextFieldDireccion.setText(trabajador.registro(regemp1).getDireccion());
      jTextFieldCURP.setText(trabajador.registro(regemp1).getCurp());
      jTextFieldSueldoD.setText(sueldoD);
      jTextFieldDiasLab.setText(diasl);
      // jLabelSueldoTotal.setVisible(false);
      // jTextFieldSueldoTotal.setVisible(false);
      jTextFieldEmail.setText(trabajador.registro(regemp1).getEmail());
      jTextFieldAntiguedad.setText(trabajador.registro(regemp1).getAntiguedad());
      caso = 4;
      jDialog1.setVisible(true);
    }
  }

  // Metodo bajas

  public void bajas() {
    String numemp = JOptionPane.showInputDialog("Escriba el número de empleado" + " del registro que desea eliminar: ");

    ne = Integer.parseInt(numemp);
    regemp1 = trabajador.buscarParaCam(ne);

    if (ne == -1)
      JOptionPane.showMessageDialog(null, "No se encontró ningún registro");
    else {
      jDialog1.setLocation(400, 200);
      jDialog1.setTitle("Bajas");
      jButton1.setText("Eliminar");
      // jLabelSueldoTotal.setVisible(true);
      // jTextFieldSueldoTotal.setVisible(true);

      String numeroemp = String.valueOf(trabajador.registro(regemp1).getNumEmp());

      String sueldodia = String.valueOf(trabajador.registro(regemp1).getSueldoDiario());
      String diastra = String.valueOf(trabajador.registro(regemp1).getDiasLab());
      String sueldotot = String.valueOf(trabajador.registro(regemp1).getSueldoTotal());

      jTextFieldNumEmp.setText(numeroemp);

      jTextFieldNombre.setText(trabajador.registro(regemp1).getNombre());
      jTextFieldApellidopaterno.setText(trabajador.registro(regemp1).getApellidopaterno());
      jTextFieldApellidomaterno.setText(trabajador.registro(regemp1).getApellidomaterno());
      jTextFieldDireccion.setText(trabajador.registro(regemp1).getDireccion());
      jTextFieldCURP.setText(trabajador.registro(regemp1).getCurp());
      jTextFieldSueldoD.setText(sueldodia);
      jTextFieldDiasLab.setText(diastra);
      // jTextFieldSueldoTotal.setText(sueldotot);
      jTextFieldEmail.setText(trabajador.registro(regemp1).getEmail());
      jTextFieldAntiguedad.setText(trabajador.registro(regemp1).getAntiguedad());
      caso = 3;
      jDialog1.setVisible(true);
    }
  }

  public String leerTxt(String direccion) { // direccion del archivo

    String texto = "";

    try {
      BufferedReader bf = new BufferedReader(new FileReader(direccion));
      String temp = "";
      String bfRead;
      while ((bfRead = bf.readLine()) != null) {
        // haz el ciclo, mientras bfRead tiene datos
        temp = temp + bfRead; // guardado el texto del archivo
      }

      texto = temp;

    } catch (Exception e) {
      System.err.println("No se encontro archivo");
    }

    return texto;

  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Altas().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButtonCancelar;
  private javax.swing.JComboBox<String> jComboBoxFacultad;
  private javax.swing.JComboBox<String> jComboBoxFacultadPertenencia;
  private javax.swing.JComboBox<String> jComboBoxFacultadPertenenciaAyudante;
  private javax.swing.JComboBox<String> jComboBoxNivel;
  private javax.swing.JComboBox<String> jComboBoxNivelAyudante;
  private javax.swing.JComboBox<String> jComboBoxNivelProfesor;
  private javax.swing.JComboBox<String> jComboBoxPasanteoTitulado;
  private javax.swing.JComboBox<String> jComboBoxPuesto;
  private javax.swing.JDialog jDialog1;
  private javax.swing.JLabel jLabelAntiguedad;
  private javax.swing.JLabel jLabelApellidomaterno;
  private javax.swing.JLabel jLabelApellidopaterno;
  private javax.swing.JLabel jLabelCURP;
  private javax.swing.JLabel jLabelClaseImpartida;
  private javax.swing.JLabel jLabelClaseImpartidaAyudante;
  private javax.swing.JLabel jLabelDiasLab;
  private javax.swing.JLabel jLabelDireccion;
  private javax.swing.JLabel jLabelEmail;
  private javax.swing.JLabel jLabelFacultad;
  private javax.swing.JLabel jLabelFacultadPertenencia;
  private javax.swing.JLabel jLabelFacultadPertenenciaAyudante;
  private javax.swing.JLabel jLabelHorarioAdmi;
  private javax.swing.JLabel jLabelHorarioClase;
  private javax.swing.JLabel jLabelHorarioClaseAyudante;
  private javax.swing.JLabel jLabelInvestigador;
  private javax.swing.JLabel jLabelLugarTrabajoAdmi;
  private javax.swing.JLabel jLabelNivelAyudante;
  private javax.swing.JLabel jLabelNivelProfesor;
  private javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelNumEmp;
  private javax.swing.JLabel jLabelPasanteoTitulado;
  private javax.swing.JLabel jLabelPorcentajeCreditos;
  private javax.swing.JLabel jLabelPuesto;
  private javax.swing.JLabel jLabelPuestoAdmi;
  private javax.swing.JLabel jLabelSNI;
  private javax.swing.JLabel jLabelSueldoDiario;
  private javax.swing.JLabel jLabelTitulo;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanelAdministrativo;
  private javax.swing.JPanel jPanelAyudante;
  private javax.swing.JPanel jPanelInvestigador;
  private javax.swing.JPanel jPanelProfesor;
  private javax.swing.JTextField jTextFieldAntiguedad;
  private javax.swing.JTextField jTextFieldApellidomaterno;
  private javax.swing.JTextField jTextFieldApellidopaterno;
  private javax.swing.JTextField jTextFieldCURP;
  private javax.swing.JTextField jTextFieldClaseImpartida;
  private javax.swing.JTextField jTextFieldClaseImpartidaAyudante;
  private javax.swing.JTextField jTextFieldDiasLab;
  private javax.swing.JTextField jTextFieldDireccion;
  private javax.swing.JTextField jTextFieldEmail;
  private javax.swing.JTextField jTextFieldHorarioAdmi;
  private javax.swing.JTextField jTextFieldHorarioAyudante;
  private javax.swing.JTextField jTextFieldHorarioClase;
  private javax.swing.JTextField jTextFieldLugarTrabajoAdmi;
  private javax.swing.JTextField jTextFieldNombre;
  private javax.swing.JTextField jTextFieldNumEmp;
  private javax.swing.JTextField jTextFieldPorcentajeCreditos;
  private javax.swing.JTextField jTextFieldPuestoAdmi;
  private javax.swing.JTextField jTextFieldSNI;
  private javax.swing.JTextField jTextFieldSueldoD;
  private javax.swing.JTextField jTextFieldTitulo;
  // End of variables declaration
}
