/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Tarea 0
 * 
 * @author Gallegos Mota Victor Hugo, Carlos Cruz Rangel
 *
 *         Esta es la interfaz (GUI) que será mostrada en pantalla para la
 *         captura por parte del usuario.
 */
public class Nomina extends javax.swing.JFrame {
    private Registros trabajador;
    int l;

    /**
     * Creates new form Nomina
     */
    public Nomina() {
        initComponents();
        jDialog1.setVisible(false);
        jTextArea1.setVisible(false);
        abrirArchivo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        registroMenu = new javax.swing.JMenu();
        jMenuItemAltas = new javax.swing.JMenuItem();
        jMenuItemBajas = new javax.swing.JMenuItem();
        jMenuItemCambios = new javax.swing.JMenuItem();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        jMenuItemMostrarTodos = new javax.swing.JMenuItem();
        jMenuItemGenerar = new javax.swing.JMenuItem();
        ayudaMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE));

        archivoMenu.setText("Archivo");

        jMenuItemGuardar.setText("Guardar");
        jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarActionPerformed(evt);
            }
        });
        archivoMenu.add(jMenuItemGuardar);

        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(exitMenuItem);

        jMenuBar1.add(archivoMenu);

        registroMenu.setText("Registro");

        jMenuItemAltas.setText("Altas");
        jMenuItemAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltasActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemAltas);

        jMenuItemBajas.setText("Bajas");
        jMenuItemBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajasActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemBajas);

        jMenuItemCambios.setText("Cambios");
        jMenuItemCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiosActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemCambios);

        jMenuItemBuscar.setText("Buscar trabajador");
        jMenuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemBuscar);

        jMenuItemMostrarTodos.setText("Mostrar todos");
        jMenuItemMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarTodosActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemMostrarTodos);

        jMenuItemGenerar.setText("Generar Pagos de Nomina");
        jMenuItemGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerarActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemGenerar);

        jMenuBar1.add(registroMenu);

        ayudaMenu.setText("Ayuda");

        aboutMenuItem.setText("Mas info");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(aboutMenuItem);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addComponent(jPanel1,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        pack();
    }// </editor-fold>

    private void jMenuItemAltasActionPerformed(java.awt.event.ActionEvent evt) {
        Altas altas = new Altas();
        altas.setVisible(true);
        altas.setTitle("Altas");

    }

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(null, "Tarea 0: \n" + "Modelado y programacion \n" + "Versión: 1.0.0\n"
                + "Creado por: Gallegos Mota Victor Hugo y Carlos Cruz Rangel\n" + "Desarrollado con el \u2764 \n"
                + "Semestre 2022-1 \n" + "Contacto: 316160456@ciencias.unam.mx, carloscruzrangel@ciencias.unam.mx");
    }

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        guardarArchivo();
        System.exit(0);
    }

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardarArchivo();
    }

    private void jMenuItemBajasActionPerformed(java.awt.event.ActionEvent evt) {
        FileWriter aux = null; // copia
        String trabajadorNum = "Victor"; // apunta a quien eliminar
        File original = new File("Nomina.txt"); // original
        Scanner sc = null; // leer del archivo orignial
        BufferedWriter writer = null;
        try {
            if (original.exists()) {
                aux = new FileWriter("Temporal.txt");
                writer = new BufferedWriter(aux);
                sc = new Scanner(original);
                String linea = " ";
                while (sc.hasNextLine()) {
                    linea = sc.nextLine();
                    if (!linea.contains(trabajadorNum)) {
                        writer.write(linea + "\n");
                    }
                }
                sc.close();
                original.delete();
                writer.close();
                aux.close();
                File file = new File("Temporal.txt");
                file.renameTo(original);
            }
        } catch (IOException ex) {
            Logger.getLogger(Nomina.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                writer.close();
                aux.close();
            } catch (IOException ex) {

            }
        }
    }

    private void jMenuItemCambiosActionPerformed(java.awt.event.ActionEvent evt) {
        Altas actualizar = new Altas();
        actualizar.actualizar();
    }

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {
        Altas buscar = new Altas();
        buscar.buscar();
    }

    private void jMenuItemMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {
        jTextArea1.setText("");

        Altas texto = new Altas();
        String s1 = texto.leerTxt("Nomina.txt");

        System.out.println("\n " + s1);

        jTextArea1.setVisible(true);

    }

    private void jMenuItemGenerarActionPerformed(java.awt.event.ActionEvent evt) {
        jTextArea1.setText("");

        for (int i = 0; i < trabajador.longitud(); i++) {
            String numeroemp = String.valueOf(trabajador.registro(i).getNumEmp());

            String sueldodia = String.valueOf(trabajador.registro(i).getSueldoDiario());
            String diastra = String.valueOf(trabajador.registro(i).getDiasLab());
            String sueldotot = String.valueOf(trabajador.registro(i).getSueldoTotal());
            jTextArea1.append("\n                           "
                    + "                                                                FACULTAD DE CIENCIAS\n"
                    + "                      Comprobante de pago"
                    + "                                                                               "
                    + "                                                        Folio " + (i + 1) + "\n\n");
            jTextArea1.append("Número de trabajador: " + numeroemp + "  Nombre: " + trabajador.registro(i).getNombre()
                    + " " + trabajador.registro(i).getApellidopaterno() + " "
                    + trabajador.registro(i).getApellidomaterno() + "  Direccion: "
                    + trabajador.registro(i).getDireccion() + "  CURP:  " + trabajador.registro(i).getCurp() + "\n"
                    + "                   Sueldo por día :  " + sueldodia + "\n" + "                   Días laborados: "
                    + diastra + "\n" + "                   Sueldo total:  " + sueldotot + "  Email: "
                    + trabajador.registro(i).getEmail() + "  Años de antiguedad: "
                    + trabajador.registro(i).getAntiguedad() + "\n"
                    + "                                                     "
                    + "                                                     "
                    + "                   Firma de recibido:______________________\n"
                    + "------------------------------------------------------"
                    + "------------------------------------------------------"
                    + "------------------------------------------------------");
        }
        jTextArea1.setVisible(true);
    }

    /**
     * Se abre el flujo de datos hacía el archivo "nomina.txt"
     */
    private void abrirArchivo() {
        File archivo = new File("nomina.txt");

        /**
         * Se verifica si existe el archivo, de no ser así se crea "nomina.txt", si el
         * archivo existe se abre el flujo hacia este.
         */
        if (!archivo.exists()) {
            trabajador = new Registros();
            JOptionPane.showMessageDialog(null, "Se ha creado una nómina nueva");
        } else {
            try {
                ObjectInputStream ois = new ObjectInputStream(new FileInputStream("nomina.txt"));
                trabajador = (Registros) ois.readObject();
                ois.close();
                JOptionPane.showMessageDialog(null, "Se cargó la nómina con éxito");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }

    /**
     * Se escriben los datos y se cierra el flujo en el archivo "nomina.txt"
     */
    public void guardarArchivo() {
        try {
            ObjectOutputStream fos = new ObjectOutputStream(new FileOutputStream("nomina.txt"));
            fos.writeObject(trabajador);
            fos.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAltas;
    private javax.swing.JMenuItem jMenuItemBajas;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuItemCambios;
    private javax.swing.JMenuItem jMenuItemGenerar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemMostrarTodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu registroMenu;
    // End of variables declaration
}
